### ISSUE TITLE
Installation guide for Linux

### ISSUE THREAD

**Issue by akihironitta** [jasperapp/jasper#190]
Do you have installation guide for linux? Is there anything I should install beforehand?

I am interested in using jasper on Debian 10, but I cannot use it due to the following error.
In particular, I ran:
```shell
wget https://www.dropbox.com/s/dwydsq18u82zgeu/jasper_v1.0.2_linux.zip
unzip jasper_v1.0.2_linux.zip
cd Jasper
sudo ./Jasper --no-sandbox
```
, and I got the following error message:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.ImqdEP)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/nitta/tmp/Jasper/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
```

Thank you in advance!

**Comment by akihironitta** [comment]
Any updates?
